INSERT INTO CLIENT(ID, NAME, TYPE) VALUES (1, 'Big company', 'LEGAL_PERSON')
INSERT INTO CLIENT(ID, NAME, TYPE) VALUES (2, 'Small company', 'LEGAL_PERSON')
INSERT INTO CLIENT(ID, NAME, TYPE) VALUES (3, 'Individual entrepreneur', 'NATURAL_PERSON')
